const path = require('path');
const fs = require('fs');
const { PDFDocument } = require('pdf-lib');
const { exec } = require('child_process');

async function convertDocument(file, targetFormat, settings) {
    const inputPath = file.path;
    const outputFilename = `converted-${Date.now()}.${targetFormat}`;
    const tempDir = path.join(__dirname, '../temp');
    const outputPath = path.join(tempDir, outputFilename);
    const originalExt = path.extname(file.originalname).toLowerCase();

    // Specific handling for PDF -> PDF (e.g. merge/split - we'll do a simple copy for now)
    if (originalExt === '.pdf' && targetFormat === 'pdf') {
        const pdfBytes = fs.readFileSync(inputPath);
        const pdfDoc = await PDFDocument.load(pdfBytes);
        const newPdf = await PDFDocument.create();
        
        const copiedPages = await newPdf.copyPages(pdfDoc, pdfDoc.getPageIndices());
        copiedPages.forEach((page) => newPdf.addPage(page));

        const newPdfBytes = await newPdf.save();
        fs.writeFileSync(outputPath, newPdfBytes);
        return outputPath;
    }

    // LibreOffice Headless for everything else (DOCX, TXT, PDF, RTF, ODT, HTML)
    return new Promise((resolve, reject) => {
        // LibreOffice keeps the original filename but changes the extension
        // e.g. input.docx -> input.pdf
        const cmd = `soffice --headless --convert-to ${targetFormat} "${inputPath}" --outdir "${tempDir}"`;

        exec(cmd, (error, stdout, stderr) => {
            if (error) {
                return reject(new Error(`Document conversion failed. Ensure LibreOffice is installed and added to PATH. Error: ${error.message}`));
            }
            
            // Reconstruct the expected output filename from LibreOffice
            const expectedLibreOfficeOutput = path.join(tempDir, path.basename(inputPath, originalExt) + '.' + targetFormat);
            
            if (fs.existsSync(expectedLibreOfficeOutput)) {
                // Rename it to our standardized converted timestamp filename
                fs.renameSync(expectedLibreOfficeOutput, outputPath);
                resolve(outputPath);
            } else {
                reject(new Error('Document conversion failed: Output file not generated by LibreOffice.'));
            }
        });
    });
}

module.exports = { convertDocument };
